services:
  database:
    image: dv1676-database
    container_name: database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.4
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./db/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    restart: always

  restapi:
    image: dv1676-restapi
    container_name: restapi
    ports:
      - "5001:5001"
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.3
    restart: always
    depends_on:
      - database

  client:
    image: dv1676-client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.2
    restart: always
    depends_on:
      - restapi

  simulation:
    image: dv1676-simulation
    container_name: simulation
    ports:
      - "1337:1337"
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.5
    restart: always
    depends_on:
      - restapi

networks:
    dv1676-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16
