services:
  restapi:
    image: dv1676-restapi
    container_name: restapi
    ports:
      - "5000:5000"
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.2
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: on-failure

  client:
    image: dv1676-client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.1
    restart: always
    depends_on:
      - restapi

networks:
    dv1676-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16
