services:
  database:
    image: mariadb
    container_name: database
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci
    env_file:
      - .env
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.4
    entrypoint:
      - docker-entrypoint.sh
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./db/01-magicbike_backup.sql:/docker-entrypoint-initdb.d/01-magicbike_backup.sql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always

  restapi:
    image: dv1676-restapi
    container_name: restapi
    ports:
      - "1337:1337"
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.3
    restart: always
    depends_on:
      - database

  client:
    image: dv1676-client
    container_name: client
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.2
    restart: always
    depends_on:
      - restapi

  simulation:
    image: dv1676-simulation
    container_name: simulation
    ports:
      - "5001:5001"
    networks:
      dv1676-network:
        ipv4_address: 172.22.0.5
    restart: always
    depends_on:
      - restapi

networks:
    dv1676-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.22.0.0/16
